baseurl = "https://elradar.github.io"
languageCode = "es-ar"
copyright = "equipo el RadaR"
summaryLength = 25
title = "el RadaR"
theme = "mediumish-gohugo-theme"
googleAnalytics = ""
#disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/nodejh"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "posts"
    weight = 200
    identifier = "bog"
    url = "/post"


[params]
 # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    logo = "/images/logo.png"
    
    author = "equipo el RadaR"
	description = "detectando los paquetes y proyectos en R que tenes que conocer"
	
[params.social]
#  github = "<username>"
#  linkedin = "<username>"
#  xing = "<username>"
#  medium = "<username>"
   twitter = "_elradar_"
#  instagram = "<username>"


[params.index]
  picture = "/images/elradar_logo.png"
  title = "esto es el RadaR"
  subtitle = "detectando los paquetes y proyectos en R que tenes que conocer"
  mdtext = '''
  Queremos usar este sitio como plataforma para mostrar los recursos de R que no te podés perder y la forma de contactarte con sus autores.<br/>
  Nos podés [seguir en Twitter](www.twitter.com/_elradar_) y escribirnos a [plataformaelradar@gmail.com](mailto:plataformaelradar@gmail.com).<br/>
  Si no sabés usar R y querés aprender, podés empezar por [aquí](https://bitsandbricks.github.io/ciencia_de_datos_gente_sociable/)
'''
  alertbar = false
